### PR TITLE
fix MapEntry not found error in clj

### LINKED ISSUE #54: regression in 0.19.5
When I try to use `x/for` in a `defmacro` I get the following error:

```
; clojure -Sdeps '{:deps {net.cgrand/xforms {:mvn/version "0.19.5"}}}' -M -e '(do (require \'[net.cgrand.xforms :as x]) (defmacro foo [] (x/for [a _] a)))'
Syntax error compiling at (REPL:1:59).
No such var: net.cgrand.xforms/MapEntry
```

It works with 0.19.4:

```
; clojure -Sdeps '{:deps {net.cgrand/xforms {:mvn/version "0.19.4"}}}' -M -e '(do (require \'[net.cgrand.xforms :as x]) (defmacro foo [] (x/for [a _] a)))'
#'user/foo
```

### PR DESCRIPTION
**Pull request by imrekoszo**
Fixes #54

### CODE REVIEW

**Comment by imrekoszo** [comment]
@cgrand `bb test-all` passes for me. I don't have ClojureDart to try it out there, would you be able to verify I didn't break that please?

**Comment by cgrand** [comment]
Go ahead. I won't bother with clojudart being broken until I fix the reader issues that make cljc painful in clojuredart.

**Comment by imrekoszo** [comment]
Force-pushed to add a test, no change to the fix itself.

**Comment by imrekoszo** [comment]
```
git show --shortstat && bb test-all
commit 3b432f9cec5d84e8593dc8ce5043de3704ce0d48 (HEAD -> issue-54, imre/issue-54)
Author: Imre Kószó <imrekoszo@users.noreply.github.com>
Date:   Mon Jan 22 11:33:34 2024 +0100

    cut 0.19.6

 2 files changed, 9 insertions(+), 1 deletion(-)

Testing net.cgrand.xforms-test

Ran 8 tests containing 42 assertions.
0 failures, 0 errors.
+ clojure -Srepro -M:kaocha:test:clj-1-9
[(...............................................)]
10 tests, 47 assertions, 0 failures.
+ clojure -Srepro -M:kaocha:test:clj-1-10
[(...............................................)]
10 tests, 47 assertions, 0 failures.
+ clojure -Srepro -M:kaocha:test:clj-1-11
[(...............................................)]
10 tests, 47 assertions, 0 failures.

Testing net.cgrand.xforms-test

Ran 8 tests containing 42 assertions.
0 failures, 0 errors.

Testing net.cgrand.xforms-test

Ran 8 tests containing 42 assertions.
0 failures, 0 errors.
```

**Pull request merged**
